// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRsCgjggBRuJbERbIVNhvFBTw-XIdmL6w',
    appId: '1:138782443693:web:8b39b04a5d52467d951e24',
    messagingSenderId: '138782443693',
    projectId: 'todo-manager-c5560',
    authDomain: 'todo-manager-c5560.firebaseapp.com',
    storageBucket: 'todo-manager-c5560.firebasestorage.app',
    measurementId: 'G-DDBJE88E7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXLtequ2w-s9a7brUCk2Na4rymy-gqbWg',
    appId: '1:138782443693:android:586dcc1fb6d08278951e24',
    messagingSenderId: '138782443693',
    projectId: 'todo-manager-c5560',
    storageBucket: 'todo-manager-c5560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3WLzLH6_LCdcUivJ4zwJbnvVx1ezc6A',
    appId: '1:138782443693:ios:11dd5e0865ee79fd951e24',
    messagingSenderId: '138782443693',
    projectId: 'todo-manager-c5560',
    storageBucket: 'todo-manager-c5560.firebasestorage.app',
    iosBundleId: 'com.example.todoManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm3WLzLH6_LCdcUivJ4zwJbnvVx1ezc6A',
    appId: '1:138782443693:ios:11dd5e0865ee79fd951e24',
    messagingSenderId: '138782443693',
    projectId: 'todo-manager-c5560',
    storageBucket: 'todo-manager-c5560.firebasestorage.app',
    iosBundleId: 'com.example.todoManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRsCgjggBRuJbERbIVNhvFBTw-XIdmL6w',
    appId: '1:138782443693:web:ca81c9de7475af14951e24',
    messagingSenderId: '138782443693',
    projectId: 'todo-manager-c5560',
    authDomain: 'todo-manager-c5560.firebaseapp.com',
    storageBucket: 'todo-manager-c5560.firebasestorage.app',
    measurementId: 'G-C2DBNJTNGT',
  );
}
